# Generated by Django 4.0.5 on 2022-06-18 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankingapp.groups')),
            ],
        ),
        migrations.CreateModel(
            name='Particulars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('particualrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankingapp.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankingapp.particulars')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankingapp.account')),
                ('particualrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankingapp.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankingapp.particulars')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankingapp.account')),
                ('particualrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankingapp.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankingapp.particulars')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankingapp.account')),
                ('particualrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankingapp.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='transactiontype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactiontype', models.CharField(max_length=225)),
            ],
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.AddField(
            model_name='sales',
            name='transactiontype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankingapp.transactiontype'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='transactiontype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankingapp.transactiontype'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transactiontype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankingapp.transactiontype'),
        ),
        migrations.AddField(
            model_name='contra',
            name='amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankingapp.particulars'),
        ),
        migrations.AddField(
            model_name='contra',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankingapp.account'),
        ),
        migrations.AddField(
            model_name='contra',
            name='particualrs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankingapp.ledger'),
        ),
        migrations.AddField(
            model_name='contra',
            name='transactiontype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankingapp.transactiontype'),
        ),
        migrations.AddField(
            model_name='account',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankingapp.ledger'),
        ),
    ]
