# Generated by Django 4.0.5 on 2022-06-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0002_account_contra_groups_ledger_particulars_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contra',
            name='date',
        ),
    ]
