# Generated by Django 4.0.5 on 2022-06-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0003_remove_contra_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contra',
            name='amount',
        ),
        migrations.AlterField(
            model_name='contra',
            name='particualrs',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contra',
            name='transactiontype',
            field=models.CharField(max_length=10),
        ),
    ]
