# Generated by Django 4.0.5 on 2022-06-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0004_remove_contra_amount_alter_contra_particualrs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contra',
            name='amount',
            field=models.IntegerField(default=False),
        ),
    ]
