# Generated by Django 4.0.5 on 2022-06-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0005_contra_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ledger_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='group',
        ),
        migrations.RemoveField(
            model_name='particulars',
            name='particualrs',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='date',
        ),
        migrations.AddField(
            model_name='contra',
            name='instrument_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contra',
            name='instrument_no',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='instrument_date',
            field=models.DateField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='instrument_no',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='receipt',
            name='instrument_date',
            field=models.DateField(default=False),
        ),
        migrations.AddField(
            model_name='receipt',
            name='instrument_no',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='sales',
            name='instrument_date',
            field=models.DateField(default=False),
        ),
        migrations.AddField(
            model_name='sales',
            name='instrument_no',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='particualrs',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transactiontype',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='amount',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='particualrs',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='transactiontype',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sales',
            name='amount',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='sales',
            name='particualrs',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sales',
            name='transactiontype',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='account',
        ),
        migrations.DeleteModel(
            name='groups',
        ),
        migrations.DeleteModel(
            name='ledger',
        ),
        migrations.DeleteModel(
            name='Particulars',
        ),
        migrations.DeleteModel(
            name='transactiontype',
        ),
    ]
