# Generated by Django 4.0.5 on 2022-06-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0006_bank_name_ledger_name_remove_ledger_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contra',
            name='instrument_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='instrument_date',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='instrument_date',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='instrument_date',
        ),
    ]
