# Generated by Django 4.0.5 on 2022-06-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0008_groups_ledger_transactiontype_particulars_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contra',
            name='instrument_no',
        ),
    ]
