# Generated by Django 4.0.5 on 2022-06-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0009_remove_contra_instrument_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='instrument_no',
        ),
    ]
