# Generated by Django 4.0.5 on 2022-06-20 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0010_remove_payment_instrument_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='instrument_no',
        ),
    ]
